# Generated by Django 4.2 on 2023-04-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('daraja', models.CharField(choices=[("Boshlang'ich", "Boshlang'ich"), ("O'rta", "O'rta"), ('Yuqori', 'Yuqori')], max_length=12)),
                ('ustoz', models.CharField(max_length=20)),
                ('narx', models.IntegerField()),
                ('chegirma', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_fam', models.CharField(max_length=20)),
                ('yosh', models.IntegerField(null=True)),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('holat', models.CharField(choices=[('Boshlandi', 'Boshlandi'), ("Ko'rilyapti", "Ko'rilyapti"), ('Tugadi', 'Tugadi')], max_length=11)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_02.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_02.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Talangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_02.kurs')),
                ('prifile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_02.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=100)),
                ('sana', models.DateField()),
                ('baho', models.IntegerField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_02.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_02.profil')),
            ],
        ),
    ]
