# Generated by Django 4.2 on 2023-04-15 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=10)),
                ('ish_vaqti', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('sahifa', models.IntegerField()),
                ('janr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('kitoblar_soni', models.SmallIntegerField()),
                ('jins', models.CharField(choices=[('Ayol', 'Ayol'), ('Ekak', 'Erkak'), ('Berilmagan', 'Berilmagan')], max_length=10)),
                ('tirik', models.BooleanField()),
                ('tugilgan_yili', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('kitoblar_soni', models.IntegerField()),
                ('kusrs', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olingan_sana', models.DateField()),
                ('qaytarilish_sana', models.DateField()),
                ('qaytarildi', models.BooleanField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_01.admin')),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_01.kitob')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_01.talaba')),
            ],
        ),
        migrations.AddField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_01.muallif'),
        ),
    ]
