# Generated by Django 4.2 on 2023-04-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yangi_01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=20)),
                ('parol', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=20)),
                ('talaba', models.BooleanField()),
                ('rasm', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('daraja', models.IntegerField()),
                ('yonalish', models.CharField(max_length=10)),
                ('davomiylik', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('brend', models.CharField(max_length=10)),
                ('narx', models.IntegerField()),
                ('davlat', models.CharField(max_length=10)),
                ('mavjud', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='muallif',
        ),
        migrations.RemoveField(
            model_name='record',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='record',
            name='kitob',
        ),
        migrations.RemoveField(
            model_name='record',
            name='talaba',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Kitob',
        ),
        migrations.DeleteModel(
            name='Muallif',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Talaba',
        ),
    ]
