# Generated by Django 4.2 on 2023-04-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Yangi_01', '0002_foydalanuvchi_kurs_mahsulot_remove_kitob_muallif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('narx', models.IntegerField()),
                ('kelgan_sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nashriyot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('manzil', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_01.kitob')),
            ],
        ),
        migrations.CreateModel(
            name='Sotuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Foydalanuvchi',
        ),
        migrations.DeleteModel(
            name='Kurs',
        ),
        migrations.DeleteModel(
            name='Mahsulot',
        ),
        migrations.AddField(
            model_name='sotuv',
            name='sotuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_01.sotuvchi'),
        ),
        migrations.AddField(
            model_name='kitob',
            name='nashriyot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_01.nashriyot'),
        ),
    ]
