# Generated by Django 4.2 on 2023-04-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Yangi_01', '0004_remove_sotuv_kitob_remove_sotuv_sotuvchi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=10)),
                ('ish_vaqti', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=20)),
                ('parol', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=20)),
                ('talaba', models.BooleanField()),
                ('rasm', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('sahifa', models.IntegerField()),
                ('janr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('daraja', models.IntegerField()),
                ('yonalish', models.CharField(max_length=10)),
                ('davomiylik', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('brend', models.CharField(max_length=10)),
                ('narx', models.IntegerField()),
                ('davlat', models.CharField(max_length=10)),
                ('mavjud', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('kitoblar_soni', models.SmallIntegerField()),
                ('jins', models.CharField(choices=[('Ayol', 'Ayol'), ('Ekak', 'Erkak'), ('Berilmagan', 'Berilmagan')], max_length=10)),
                ('tirik', models.BooleanField()),
                ('tugilgan_yili', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('kitoblar_soni', models.IntegerField()),
                ('kusrs', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olingan_sana', models.DateField()),
                ('qaytarilish_sana', models.DateField()),
                ('qaytarildi', models.BooleanField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_01.admin')),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_01.kitob')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_01.talaba')),
            ],
        ),
        migrations.AddField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yangi_01.muallif'),
        ),
    ]
